/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContaine: typeof import('element-plus/es')['ElContaine']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuGroup: typeof import('element-plus/es')['ElMenuGroup']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElMeun: typeof import('element-plus/es')['ElMeun']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTree: typeof import('element-plus/es')['ElTree']
    Geometry: typeof import('./src/components/k-scene/geometry.vue')['default']
    KAsideProject: typeof import('./src/components/k-aside-project.vue')['default']
    KAsideScene: typeof import('./src/components/k-aside-scene.vue')['default']
    KHeader: typeof import('./src/components/k-header.vue')['default']
    KProp: typeof import('./src/components/k-prop.vue')['default']
    KSceneProp: typeof import('./src/components/prop/k-scene-prop.vue')['default']
    Prop: typeof import('./src/components/k-scene/prop.vue')['default']
    Textrue: typeof import('./src/components/k-scene/textrue.vue')['default']
    Texture: typeof import('./src/components/k-scene/texture.vue')['default']
  }
}
