/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTree: typeof import('element-plus/es')['ElTree']
    Geometry: typeof import('./components/k-scene/geometry.vue')['default']
    IEpAim: typeof import('~icons/ep/aim')['default']
    IEpDArrowRight: typeof import('~icons/ep/d-arrow-right')['default']
    KAsideProject: typeof import('./components/k-aside-project.vue')['default']
    KAsideScene: typeof import('./components/k-aside-scene.vue')['default']
    KHeader: typeof import('./components/k-header.vue')['default']
    KProp: typeof import('./components/k-prop.vue')['default']
    Prop: typeof import('./components/k-scene/prop.vue')['default']
    Textrue: typeof import('./components/k-scene/textrue.vue')['default']
  }
}
